import type { Readable } from 'node:stream';

export interface PutObjectInput {
	/** Driver-relative path. Always generated by `buildStorageKey`, never user input. */
	key: string;
	body: Buffer | Uint8Array | Readable;
	contentType: string;
	/** Bytes, used by drivers that need the length up front. */
	contentLength?: number;
	/** Display name, returned in `Content-Disposition` on download. */
	originalName?: string;
}

export interface StoredObject {
	key: string;
	sizeBytes: number;
	/** Hex SHA-256 of the stored bytes. */
	checksum: string;
}

export interface GetObjectResult {
	stream: Readable;
	sizeBytes: number;
	contentType: string;
}

/**
 * The contract every storage backend implements.
 *
 * Deliberately narrow: no listing, no public URLs, no bucket management. Files in
 * this product (resumes, ID documents, offer letters) are never publicly readable —
 * access always goes through an authorized app route, so a driver that could hand
 * out a public URL would be an attractive way to accidentally leak one.
 */
export interface StorageDriver {
	readonly name: 'local' | 's3';
	put(input: PutObjectInput): Promise<StoredObject>;
	get(key: string): Promise<GetObjectResult>;
	delete(key: string): Promise<void>;
	exists(key: string): Promise<boolean>;
}

export class StorageObjectNotFound extends Error {
	constructor(key: string) {
		super(`No stored object for key: ${key}`);
		this.name = 'StorageObjectNotFound';
	}
}
